### PR TITLE
Call onHeaders asynchronously with later()

### LINKED ISSUE #96: Incorrect behavior with onHeaders
As of httpuv 1.3.5, the `onHeaders()` function does some things incorrectly.

With this test app:

```R
runServer("0.0.0.0", 5000,
  list(
    onHeaders = function(req) {
      list(
        status = 200L,
        headers = list('Content-Type' = 'text/html'),
        body = "abc"
      )
    } 
  )
)
```

Then do a `GET /`:

```
$ nc localhost 5000
GET /

HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 3
```

Two things happen incorrectly (I think):

1. It doesn't return the body ("abc").
2. In the R side, it says there's a parse error, as in `ERROR: [on_request_read] parse error`.

I just tested with Shiny, and indeed it doesn't send the body [here](https://github.com/rstudio/shiny/blob/ba8d79f/R/middleware.R#L303).

After the server sends the data, it closes the connection. This differs from the behavior when `$call()` is used, where the server does not close the connection. Is the disconnection expected?

```
> sessioninfo::session_info()
─ Session info ────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       macOS Sierra 10.12.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Chicago             
 date     2017-10-24                  

─ Packages ────────────────────────────────────────────────────────────────────────
 package     * version date       source         
 clisymbols    1.2.0   2017-05-21 cran (@1.2.0)  
 httpuv      * 1.3.5   2017-07-04 CRAN (R 3.4.1) 
 Rcpp          0.12.13 2017-09-28 cran (@0.12.13)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.1) 
 withr         2.0.0   2017-07-28 cran (@2.0.0)  
 yaml          2.1.14  2016-11-12 CRAN (R 3.4.0) 
```

### PR DESCRIPTION
**Pull request by wch**
This pull request uses `later()` to call the user's `onHeaders()` function asynchronously. This is a necessary step for running the I/O on a background thread, but I thought it deserved its own PR and code review.

This also fixes #96.

### CODE REVIEW

File: src/http-parser/http_parser.c [hunk 1]
```diff
@@ -2090,6 +2151,14 @@ size_t http_parser_execute (http_parser *parser,
   RETURN(p - data);
 }
 
+void http_parser_on_headers_completed(http_parser *parser) {
```
Comment (wch) [inline src/http-parser/http_parser.c]: Should check `is_running` here and error if true.

File: src/http-parser/http_parser.c [hunk 2]
```diff
@@ -2150,12 +2219,18 @@ http_parser_init (http_parser *parser, enum http_parser_type t)
   parser->type = t;
   parser->state = (t == HTTP_REQUEST ? s_start_req : (t == HTTP_RESPONSE ? s_start_res : s_start_req_or_res));
   parser->http_errno = HPE_OK;
+
+  parser->is_running = 0;
+  parser->waiting_for_headers_completed = 0;
```
Comment (wch) [inline src/http-parser/http_parser.c]: Might be better to have a function that returns true if state is `s_wait_for_on_headers_completed`.

File: src/http-parser/http_parser.c [hunk 3]
```diff
@@ -2150,12 +2219,18 @@ http_parser_init (http_parser *parser, enum http_parser_type t)
...
+  parser->headers_status = -1;
 }
 
 void
 http_parser_settings_init(http_parser_settings *settings)
 {
   memset(settings, 0, sizeof(*settings));
+  /* Default is to expect synchronous on_headers_complete. */
+  settings->is_async_on_headers_complete = 0;
```
Comment (wch) [inline src/http-parser/http_parser.c]: Not necessary since the memory is zeroed out. Same with above.

File: src/http.cpp [hunk 4]
```diff
@@ -211,48 +233,85 @@ int HttpRequest::_on_header_value(http_parser* pParser, const char* pAt, size_t
...
+  this->_pWebApplication->onHeaders(
+    this,
+    boost::bind(&HttpRequest::_on_headers_complete_complete, this, _1)
+  );
+}
+
+// This wrapper function is needed to use HttpRequest::_call_r_on_headers with
+// later(). That method can't be passed to later(), but this function can.
+void call_r_on_headers_wrapper(void* data) {
+  HttpRequest* req = (HttpRequest*) data;
```
Comment (jcheng5) [inline src/http.cpp]: Use a C++ style cast

File: src/http.cpp [hunk 5]
```diff
@@ -211,48 +233,85 @@ int HttpRequest::_on_header_value(http_parser* pParser, const char* pAt, size_t
...
     }
   }
 
-  // TODO: Allocate body
-  return result;
+  // Tell the parser what the result was.
+  this->_parser.headers_status = result;
+
+  // Tell the http parser it can move on.
+  http_parser_on_headers_completed(&(this->_parser));
```
Comment (wch) [inline src/http.cpp]: Combine this and previous line into a single function call.

Rename function to `http_parser_set_headers_result`, or something like that.

File: src/http.cpp [hunk 6]
```diff
@@ -303,50 +362,74 @@ void HttpRequest::close() {
   uv_close(toHandle(&_handle.stream), HttpRequest_on_closed);
 }
 
+void HttpRequest::_parse_http_data(char* buffer, const ssize_t n) {
+  int parsed = http_parser_execute(&_parser, &request_settings(), buffer, n);
+
+  if (_parser.waiting_for_headers_completed) {
+    // If we're waiting for the header response, just store the data in the
+    // buffer.
+    _requestBuffer.append(buffer + parsed, n - parsed);
```
Comment (wch) [inline src/http.cpp]: Change `_requestBuffer` to a `vector<char>`.

**Comment by wch** [comment]
@jcheng5 I've addressed all the issues we discussed in the review, with one exception: I left the explicit initialization to 0 for clarity.
