### PR TITLE
Use correct keep-alive behavior

### LINKED ISSUE #98: Parse error with persistent connections
If you run an app with `Connection = 'keep-alive'` and issue multiple requests to it, it prints a parse error.

Here's a simple test app:

```R
library(httpuv)
runServer("0.0.0.0", 5000,
  list(
    call = function(req) {
      list(
        status = 200L,
        headers = list(
          'Content-Type' = 'text/html',
          Connection = 'keep-alive'
        ),
        body = "abc"
      )
    } 
  )
)
```

To make multiple requests from a single connection, run:

```
nc localhost 5000
GET / HTTP/1.0

GET / HTTP/1.0

```

In the terminal, it'll look like this:

```
$ nc localhost 5000
GET / HTTP/1.0

HTTP/1.1 200 OK
Content-Type: text/html
Connection: keep-alive
Content-Length: 3

abcGET / HTTP/1.0
```

In the R session, it prints this  when it gets the second request:

```
ERROR: [on_request_read] parse error
```

With a git bisect, I found that this started happening in 1058ce2, which is very surprising, since it just changed the Makevars file. (This is on a Mac.)

Oddly, if you use `GET / HTTP/1.1` instead of `GET / HTTP/1.0`, it works fine in that commit, and it works fine on the current master (8d6486a).

### PR DESCRIPTION
**Pull request by wch**
This fixes #98. Now when either of:

* HTTP 1.0 request with no `Connection` header
* HTTP 1.1 request with a `Connection: close` header

comes in, httpuv will add a `Connection: close` **response** header and stop paying attention to incoming data.

### CODE REVIEW

File: src/http-parser/http_parser.c [hunk 1]
```diff
@@ -1869,6 +1874,10 @@ size_t http_parser_execute (http_parser *parser,
              * processing the headers, it's done with the http parser.
              */
             case 3:
+              /* If this is a keep-alive connection, we need to reset the state
+               * so that the parser can accept more messages.
+               */
+              UPDATE_STATE(NEW_MESSAGE());
```
Comment (wch) [inline src/http-parser/http_parser.c]: This is necessary because on master, the following app would erroneously close the connection:

```R
runServer("0.0.0.0", 5000,
  list(
    onHeaders = function(req) {
      list(
        status = 200L,
        headers = list('Content-Type' = 'text/html'),
        body = "abc"
      )
    }
  )
)
```

when two `GET / HTTP/1.1` requests arrived:

```
nc localhost 5000
GET / HTTP/1.1   

GET / HTTP/1.1
```

On the R side, it printed this after the second request:

```
ERROR: [on_request_read] success
```

**Comment by wch** [comment]
One odd thing is that if the R application has `Connection = "keep-alive"` and then it receives a HTTP 1.0 or Connection:close request, then it responds with:

```
Connection: keep-alive
Connection: close
```

and then closes the connection. I'm not sure the user should be playing with that header, though, since we don't give them control over the close vs. keep-alive behavior.

**Comment by wch** [comment]
I've pushed a commit which makes httpuv close a connection when the request is HTTP 1.0 or there is a `Connection: close`. This fixes #72.

Now this app can be used with apachebench:

```R
runServer("0.0.0.0", 5000,
  list(
    call = function(req) {
      list(
        status = 200L,
        headers = list('Content-Type' = 'text/html'),
        body = "abc\n"
      )
    }
  )
)
```

An example of how to run apachebench with this app:

```
ab -n 100 -c 10 http://127.0.0.1:5000/
```
